### ISSUE TITLE
Client Does Not Have JSONObject Setup Properly

### ISSUE THREAD

**Issue by NOAHBENJ** [jeremypelletier/flux-opensource#2]
I downloaded the source, to check it out you know, but when it came to using configs, it just, well crashed the game, and Java logs were complaining about the JSONObject not being defined, please rerwite it, it needs some fixing up. Thanks, NOAHBENJ!

(I am using Mac OS if that does anything, but with java 'Write once, run anywhere', it shouldn't)

**Comment by jeremypelletier** [comment]
You need to compile with the libraries and remove the IRC protection. We are only providing the source code. Maybe we will do an unlicensed release?
